services:
  # Databases
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '0806'
      MYSQL_DATABASE: 'reserva_hotel'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: '0806'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # Microservices
  usuarios:
    build: ./Usuarios_django
    container_name: usuarios_django
    ports:
      - '8001:8001'
    environment:
      - DB_HOST=postgres
      - DB_NAME=usuarios_db
      - DB_USER=postgres
      - DB_PASSWORD=0806
      - DB_PORT=5432
    depends_on:
      - postgres

  hoteles:
    build: ./Hoteles_express
    container_name: hoteles_express
    ports:
      - '8002:8002'
    environment:
      - PORT=8002
    # Firebase key is copied into the image via Dockerfile

  reservas:
    build: ./Reservas_flask
    container_name: reservas_flask
    ports:
      - '8003:8003'
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:0806@mysql/reserva_hotel
    depends_on:
      - mysql

  pagos:
    build: ./Pagos_express
    container_name: pagos_express
    ports:
      - '8004:8004'
    environment:
      - DB_HOST=postgres
      - DB_NAME=pagos_db
      - DB_USER=postgres
      - DB_PASSWORD=0806
      - DB_PORT=5432
    depends_on:
      - postgres

  resenas:
    build: ./Reseñas_flask
    container_name: resenas_flask
    ports:
      - '8005:8005'
    # Firebase key is copied into the image via Dockerfile

  gateway:
    build: ./Api_gatewey_laravel
    container_name: laravel_gateway
    ports:
      - '8000:8000'
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:pFrubHv+S+P74Dk548wyOG35t/9PaMx8jmq0KjIZKp4=
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=reserva_hotel
      - DB_USERNAME=root
      - DB_PASSWORD=0806
      - USERS_SERVICE_URL=http://usuarios:8001
      - HOTELS_SERVICE_URL=http://hoteles:8002
      - RESERVATIONS_SERVICE_URL=http://reservas:8003
      - PAYMENTS_SERVICE_URL=http://pagos:8004
      - REVIEWS_SERVICE_URL=http://resenas:8005
    depends_on:
      - mysql
      - usuarios
      - hoteles
      - reservas
      - pagos
      - resenas

volumes:
  mysql_data:
  postgres_data:
